#!/bin/bash
# ARTIX 2K26 - Quick Start Commands
# Copy and run these commands to get started

echo "🚀 ARTIX 2K26 Event Registration System"
echo "=========================================="
echo ""
echo "STEP 1: Backend Setup & Start"
echo "cd artix-backend"
echo "npm install"
echo "node initDb.js"
echo "npm start"
echo ""
echo "Output should show:"
echo "✅ Connected to MongoDB"
echo "🚀 ARTIX Server running on http://localhost:5000"
echo ""
echo "---"
echo ""
echo "STEP 2: Frontend Setup & Start (in another terminal)"
echo "cd artix-frontend"
echo "npm install"
echo "npm run dev"
echo ""
echo "Output should show:"
echo "➜  Local:   http://localhost:5173/"
echo ""
echo "---"
echo ""
echo "STEP 3: Access the Application"
echo "📋 Registration: http://localhost:5173"
echo "🔐 Admin Scanner: http://localhost:5173/admin-scan"
echo "🔌 Backend API: http://localhost:5000/api"
echo "✅ Health Check: http://localhost:5000/api/health"
echo ""
echo "---"
echo ""
echo "OPTIONAL: Run API Tests"
echo "cd artix-backend"
echo "npm test"
echo ""
echo "---"
echo ""
echo "Admin Credentials:"
echo "Password: artix2026admin"
echo ""
echo "---"
echo ""
echo "Payment Details:"
echo "UPI ID: 8919068236@ybl"
echo "Payee: PUNDRU MEGHAN REDDY"
echo ""
echo "✨ System Ready! Start registering participants."
