import { useState } from 'react';
import { CheckCircle, Copy, CheckCheck, Clock } from 'lucide-react';
import type { RegistrationFormData } from '../types/registration';

interface Props {
  registrationId: string;
  formData: RegistrationFormData;
  verificationId?: string | null;
}

export function ConfirmationPage({ registrationId, formData, verificationId }: Props) {
  const [copied, setCopied] = useState(false);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(verificationId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const darkMode = true;

  return (
    <div className={`min-h-screen transition-colors duration-300 py-6 md:py-8 px-4 flex items-center justify-center ${
      darkMode
        ? 'bg-gradient-to-br from-gray-900 via-gray-800 to-black'
        : 'bg-gradient-to-br from-white via-blue-50 to-white'
    }`}>
      <div className={`max-w-4xl w-full p-4 md:p-8 rounded-2xl border transition-all duration-300 backdrop-blur-md ${
        darkMode
          ? 'bg-gradient-to-br from-gray-800/40 via-gray-800/30 to-gray-900/40 border-gray-700/50'
          : 'bg-gradient-to-br from-white/40 via-green-50/40 to-white/40 border-gray-300/50'
      }`}>
        <div className="text-center mb-8 md:mb-12 animate-fade-in">
          <div className="inline-flex items-center justify-center w-24 md:w-32 h-24 md:h-32 bg-gradient-to-r from-green-500 to-blue-500 rounded-full mb-4 md:mb-6 animate-bounce-slow shadow-2xl">
            <CheckCircle className="w-12 md:w-16 h-12 md:h-16 text-white" />
          </div>
          <h1 className="text-3xl md:text-5xl lg:text-6xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500 mb-3 md:mb-4">
            Registration Successful! ✨
          </h1>
          <p className={`text-lg md:text-xl lg:text-2xl ${
            darkMode ? 'text-gray-300' : 'text-gray-700'
          }`}>Your registration for ARTIX 2K26 is confirmed</p>
        </div>

        {/* Registration ID - Always Shown */}
        <div className={`rounded-xl p-6 md:p-10 mb-8 border-3 text-center ${
          darkMode
            ? 'bg-gradient-to-br from-blue-500/15 to-cyan-500/15 border-blue-500/40'
            : 'bg-gradient-to-br from-blue-400/15 to-cyan-400/15 border-blue-400/40'
        }`}>
          <p className={`text-sm uppercase tracking-widest font-bold mb-4 ${
            darkMode ? 'text-blue-400' : 'text-blue-600'
          }`}>📝 Your Registration ID</p>
          
          <div className={`inline-block p-6 md:p-8 rounded-lg border-2 mb-6 ${
            darkMode
              ? 'bg-gray-900 border-blue-400'
              : 'bg-white border-blue-500'
          }`}>
            <p className={`text-3xl md:text-4xl lg:text-5xl font-mono font-bold tracking-widest break-all ${
              darkMode ? 'text-blue-400' : 'text-blue-600'
            }`}>
              {registrationId}
            </p>
          </div>

          <button
            onClick={() => {
              navigator.clipboard.writeText(registrationId);
              setCopied(true);
              setTimeout(() => setCopied(false), 2000);
            }}
            className={`inline-flex items-center gap-2 md:gap-3 px-8 md:px-10 py-4 md:py-5 rounded-lg font-bold text-base md:text-lg transition-all ${
              copied
                ? darkMode
                  ? 'bg-green-500/30 text-green-400 border border-green-500'
                  : 'bg-green-100 text-green-700 border border-green-400'
                : darkMode
                  ? 'bg-gradient-to-r from-blue-500 to-cyan-600 text-white hover:shadow-lg hover:shadow-blue-500/50'
                  : 'bg-gradient-to-r from-blue-600 to-cyan-700 text-white hover:shadow-lg'
            }`}
          >
            {copied ? (
              <>
                <CheckCheck className="w-5 h-5" /> Copied!
              </>
            ) : (
              <>
                <Copy className="w-5 h-5" /> Copy ID
              </>
            )}
          </button>

          <p className={`mt-6 text-sm md:text-base ${
            darkMode ? 'text-gray-300' : 'text-gray-700'
          }`}>
            Keep this ID safe - you'll need it to track your application status
          </p>
        </div>

        {/* Verification ID - Shown Only if Approved by Admin */}
        {verificationId ? (
          <div className={`rounded-xl p-6 md:p-10 mb-8 border-3 text-center animate-pulse ${
            darkMode
              ? 'bg-gradient-to-br from-green-500/15 to-emerald-500/15 border-green-500/40'
              : 'bg-gradient-to-br from-green-400/15 to-emerald-400/15 border-green-400/40'
          }`}>
            <p className={`text-sm uppercase tracking-widest font-bold mb-4 ${
              darkMode ? 'text-green-400' : 'text-green-600'
            }`}>✅ Your Unique Verification ID (Generated by Admin)</p>
            
            <div className={`inline-block p-6 md:p-8 rounded-lg border-2 mb-6 ${
              darkMode
                ? 'bg-gray-900 border-green-400'
                : 'bg-white border-green-500'
            }`}>
              <p className={`text-4xl md:text-5xl lg:text-6xl font-mono font-bold tracking-widest break-all ${
                darkMode ? 'text-green-400' : 'text-green-600'
              }`}>
                {verificationId}
              </p>
            </div>

            <button
              onClick={() => {
                navigator.clipboard.writeText(verificationId);
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              }}
              className={`inline-flex items-center gap-2 md:gap-3 px-8 md:px-10 py-4 md:py-5 rounded-lg font-bold text-base md:text-lg transition-all ${
                copied
                  ? darkMode
                    ? 'bg-blue-500/30 text-blue-400 border border-blue-500'
                    : 'bg-blue-100 text-blue-700 border border-blue-400'
                  : darkMode
                    ? 'bg-gradient-to-r from-green-500 to-emerald-600 text-white hover:shadow-lg hover:shadow-green-500/50'
                    : 'bg-gradient-to-r from-green-600 to-emerald-700 text-white hover:shadow-lg'
              }`}
            >
              {copied ? (
                <>
                  <CheckCheck className="w-5 h-5" /> Copied!
                </>
              ) : (
                <>
                  <Copy className="w-5 h-5" /> Copy ID
                </>
              )}
            </button>

            <p className={`mt-6 text-sm md:text-base ${
              darkMode ? 'text-gray-300' : 'text-gray-700'
            }`}>
              @{formData.email} - Save this ID - you'll need it for verification at the event
            </p>
          </div>
        )}

        {/* Awaiting Approval Message */}
        {!verificationId && (
          <div className={`p-6 md:p-10 border-3 rounded-xl mb-8 text-center ${
            darkMode
              ? 'bg-gradient-to-br from-yellow-500/15 to-orange-500/15 border-yellow-500/40'
              : 'bg-gradient-to-br from-yellow-400/15 to-orange-400/15 border-yellow-400/40'
          }`}>
            <div className="inline-flex items-center gap-3 mb-4">
              <Clock className={`w-8 h-8 ${darkMode ? 'text-yellow-400' : 'text-yellow-600'} animate-spin`} />
              <p className={`text-lg md:text-2xl font-bold ${
                darkMode ? 'text-yellow-400' : 'text-yellow-600'
              }`}>Payment Under Review</p>
            </div>
            <p className={`text-base md:text-lg ${
              darkMode ? 'text-yellow-300' : 'text-yellow-700'
            }`}>
              The admin is reviewing your payment details. Your Unique Verification ID will be generated and sent to your email once approved.
            </p>
          </div>
        )}

        {/* Your Information */}
        <div className={`rounded-xl p-6 md:p-8 mb-8 border-2 ${
          darkMode
            ? 'bg-gray-800/50 border-gray-700/50'
            : 'bg-white/50 border-gray-300/50'
        }`}>
          <h3 className={`text-lg md:text-xl font-bold mb-6 ${
            darkMode ? 'text-gray-200' : 'text-gray-800'
          }`}>Your Information</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 md:gap-6">
            <div>
              <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Name</p>
              <p className={`text-lg font-semibold mt-1 ${darkMode ? 'text-gray-200' : 'text-gray-800'}`}>
                {formData.fullName}
              </p>
            </div>
            <div>
              <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Email</p>
              <p className={`text-lg font-semibold mt-1 ${darkMode ? 'text-gray-200' : 'text-gray-800'}`}>
                {formData.email}
              </p>
            </div>
            <div>
              <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>Phone</p>
              <p className={`text-lg font-semibold mt-1 ${darkMode ? 'text-gray-200' : 'text-gray-800'}`}>
                {formData.phone}
              </p>
            </div>
          </div>
        </div>

        {/* Instructions */}
        <div className={`p-6 md:p-8 border rounded-xl ${
          darkMode
            ? 'bg-blue-500/10 border-blue-500/30'
            : 'bg-blue-50 border-blue-300'
        }`}>
          <p className={`text-base md:text-lg font-bold mb-4 ${
            darkMode ? 'text-blue-400' : 'text-blue-700'
          }`}>
            📋 What Happens Next?
          </p>
          <ol className={`text-sm md:text-base space-y-3 list-decimal list-inside ${
            darkMode ? 'text-blue-300' : 'text-blue-700'
          }`}>
            <li><strong>Admin Review:</strong> The event admin will verify your payment using the Transaction ID and UTR ID you provided in the screenshot.</li>
            <li><strong>Payment Verification:</strong> They will check that the payment amount matches the event fee (₹{formData.totalAmount || 0}).</li>
            <li><strong>Approval Decision:</strong> Admin will approve or reject your registration based on payment verification.</li>
            <li><strong>Verification ID Generation:</strong> If approved, a unique Verification ID will be generated and sent to your email.</li>
            <li><strong>Event Entry:</strong> Show your Verification ID at the event entrance for verification.</li>
          </ol>
        </div>
      </div>
    </div>
  );
}

